[project]
name = "deepvidsum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "diffsynth",
    "wan-vid-inbetween",
]

[tool.uv.workspace]
members = [
    "dep/diffsynth",
    "wan-vid-inbetween",
]

[tool.uv.sources]
diffsynth = { workspace = true }
wan-vid-inbetween = { workspace = true }
